# Generated by Django 3.1 on 2020-09-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bboy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
