# Generated by Django 3.1 on 2020-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboys', '0002_bboy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bboy',
            name='dj',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bboy',
            name='judge',
            field=models.BooleanField(null=True),
        ),
    ]
