# Generated by Django 3.1 on 2020-09-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboys', '0003_auto_20200902_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboy',
            name='judge',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
