# Generated by Django 3.1 on 2020-09-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboys', '0005_auto_20200902_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bboy',
            unique_together=set(),
        ),
    ]
